title: Kakyll
email: N/A
description: Static Site Generator in Kotlin
base_url: http://kakyll.com
deploy: call deploy_kakyll # rsync via alias manager
template_engine: handlebars
posts:
    directory: news
    template: post.hbs
pages:
    - index.hbs
    - tags.hbs
    - news.hbs
    - docs.hbs
directories:
    - assets
